name: UML to PNG Converter
on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - run: cd ./conception
    - run: echo "Conversion automatique du .du en .png ..."
    - name: Run plantuml on all .du files
    # - run: "java -jar plantuml.jar *.du"
      run: java -jar plantuml.jar *.du
    - run: echo "Succès ! UML disponible dans (???).png"
